### ISSUE TITLE
Provide releases with binaries

### ISSUE THREAD

**Issue by albfan** [dstosberg/odt2txt#10]
I'm trying to suggest usage of this program in git for windows

https://github.com/git-for-windows/build-extra/pull/148

but I'm fear it needs a link to compiled binaries. Is it possible to create releases with typical distros? (linux, windows, mac)

**Comment by dstosberg** [comment]
Sorry, I do not intent to provide binaries. If I am reading your pull request on _git-for-windows_ correctly, you have found a solutionon. Is that correct?

I don't know if it helps you, but I have a Dockerfile in the win32 directory that build a Docker image which then builds proper mingw binaries using Debian's mingw cross compiler.

**Comment by albfan** [comment]
Yes I build from sources. It is the right solution as all msys2 packages are build from sources
