### ISSUE TITLE
Support for the flat odt document format

### ISSUE THREAD

**Issue by MayeulC** [dstosberg/odt2txt#14]
Hello there,

Would it be possible to add support for the `fodt` format? This is just a flat odt xml file format (not compressed), so I imagine it should be pretty easy to do.

Opening such a file currently fails with: `Can't read from file.fodt: Is it an OpenDocument Text?`

Thanks in advance!

**Comment by stewart123579** [comment]
It's already there - see https://github.com/dstosberg/odt2txt/pull/4

If you're using a package manager (like homebrew) and are stuck on v0.5 go over to https://github.com/dstosberg/odt2txt/issues/15 and add a thumbs up and a comment...

**Comment by MayeulC** [comment]
My bad, sorry then. I use Arch linux, where it's in the community depots, and looks v0.5 is there, and supports fodt :)

it's just that the `--raw-input` isn't mentioned anywhere in the error message... If not chosen automatically, at least adding it in the message output would be nice.
But yeah, maybe this warrants a minor tag.

Thanks for this information!

Closing...
