### ISSUE TITLE
odt2txt.x86_64: W: incorrect-fsf-address /usr/share/doc/packages/odt2txt/GPL-2

### ISSUE THREAD

**Issue by radoeka** [dstosberg/odt2txt#5]
While building a package of odt2txt the following warning is shown:
 odt2txt.x86_64: W: incorrect-fsf-address /usr/share/doc/packages/odt2txt/GPL-2

Solution is mentioned here:
http://fedoraproject.org/wiki/Common_Rpmlint_issues#incorrect-fsf-address

**Comment by dstosberg** [comment]
Hi,

I updated the file to the current FSF version. Can you please verify that it fixes the warning?

Cheers,
Dennis
