### ISSUE TITLE
FWD:  odt2txt: Please add oodiff script

### ISSUE THREAD

**Issue by charles-plessy** [dstosberg/odt2txt#6]
Hi,

in Debian, a user suggested to add a script called "oodiff" to our odt2txt package.

 - Here is the link to oodiff: <http://www-verimag.imag.fr/~moy/opendocument/>
 - Here is the link to the user request: <https://bugs.debian.org/525861>

What would you think about adding it as an extra directly in odt2txt ?

Have a nice day,

-- 
Charles Plessy
Tsurumi, Kanagawa, Japan

**Comment by dstosberg** [comment]
Hi,

I know Matthieu Moy's `oodiff` script and I use it myself from time to time.

I do not think that adding the script itself to the odt2txt source distribution is useful. `oodiff` has a nicely written page there and some context that would be lost for users. And I would probably miss updates to the script.

I would rather like a pointer (maybe in `README.md`, or a `TIPS` file?) that refers to the script, its use, and its url. We could also include the tip from Debian's `README.Debian` regarding mutt there. And maybe others.

On the other hand, I would not mind if the Debian maintainer decided to add the script to the Debian packages. Packaging is the right place for such integration work.

Regards,
Dennis
