### ISSUE TITLE
Dependency on libzip-dev is not mentioned

### ISSUE THREAD

**Issue by urzds** [dstosberg/odt2txt#8]
Trying to build odt2txt on Ubuntu 14.04, I see following error:

```
# make
cc -O2   -c -o odt2txt.o odt2txt.c
odt2txt.c:42:19: fatal error: zip.h: Datei oder Verzeichnis nicht gefunden
 #  include <zip.h>
                   ^
compilation terminated.
make: *** [odt2txt.o] Fehler 1
```

Installing `libzip-dev` solves the issue. This dependency is mentioned neither in the `INSTALL` file, nor in the `README`.

**Comment by pilino1234** [comment]
Getting the same on openSUSE leap 42.2, please fix.

**Comment by albfan** [comment]
As this is not standard autotools project, there's no `pkg-config` check about that.

See libzip-dev is the develop package for ubuntu, but that's distro dependant, in other distros it is libzip-devel or libzip or zip package

Read this line should be enough:

https://github.com/dstosberg/odt2txt/blob/master/Makefile#L23

but you need to infer where your distro has the headers needed

**Comment by devurandom** [comment]
I would not require the detection to be automatic.  A simple mention of the dependencies in INSTALL (it already has a Linux section, where it claims everything odt2txt needs is the libc) and/or the README would already be sufficient.

**Comment by dstosberg** [comment]
Fixed. Thank you for noticing.
